use axum::Json;

use crate::models::{CollectionModel, Mode};

pub async fn get_collections() -> Json<Vec<CollectionModel>> {
    let collection_list: Vec<CollectionModel> = vec![
        CollectionModel {
            grp_name: "1L A1".to_string(),
            customer_name: "Raja".to_string(),
            amount: 5000.00,
            mode: Mode::CASH,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A2".to_string().to_string(),
            customer_name: "Sekar".to_string(),
            amount: 4000.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A2".to_string().to_string(),
            customer_name: "Velu".to_string().to_string(),
            amount: 7000.00,
            mode: Mode::CHEQUE,
            cheque_no: Some("SBIN56789".to_string()),
            bank: Some("State Bank of India".to_string()),
        },
        CollectionModel {
            grp_name: "5L A3".to_string(),
            customer_name: "Mani".to_string(),
            amount: 3500.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A1".to_string(),
            customer_name: "Raja".to_string(),
            amount: 5000.00,
            mode: Mode::CASH,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A2".to_string(),
            customer_name: "Sekar".to_string(),
            amount: 4000.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A2".to_string(),
            customer_name: "Velu".to_string(),
            amount: 7000.00,
            mode: Mode::CHEQUE,
            cheque_no: Some("SBIN56789".to_string()),
            bank: Some("State Bank of India".to_string()),
        },
        CollectionModel {
            grp_name: "5L A3".to_string(),
            customer_name: "Mani".to_string(),
            amount: 3500.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A1".to_string(),
            customer_name: "Raja".to_string(),
            amount: 5000.00,
            mode: Mode::CASH,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A2".to_string(),
            customer_name: "Sekar".to_string(),
            amount: 4000.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A2".to_string(),
            customer_name: "Velu".to_string(),
            amount: 7000.00,
            mode: Mode::CHEQUE,
            cheque_no: Some("SBIN56789".to_string()),
            bank: Some("State Bank of India".to_string()),
        },
        CollectionModel {
            grp_name: "5L A3".to_string(),
            customer_name: "Mani".to_string(),
            amount: 3500.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "5L A3".to_string(),
            customer_name: "Mani".to_string(),
            amount: 3500.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A1".to_string(),
            customer_name: "Raja".to_string(),
            amount: 5000.00,
            mode: Mode::CASH,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A2".to_string(),
            customer_name: "Sekar".to_string(),
            amount: 4000.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A2".to_string(),
            customer_name: "Velu".to_string(),
            amount: 7000.00,
            mode: Mode::CHEQUE,
            cheque_no: Some("SBIN56789".to_string()),
            bank: Some("State Bank of India".to_string()),
        },
        CollectionModel {
            grp_name: "5L A3".to_string(),
            customer_name: "Mani".to_string(),
            amount: 3500.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "5L A3".to_string(),
            customer_name: "Mani".to_string(),
            amount: 3500.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A1".to_string(),
            customer_name: "Raja".to_string(),
            amount: 5000.00,
            mode: Mode::CASH,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A2".to_string(),
            customer_name: "Sekar".to_string(),
            amount: 4000.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
        CollectionModel {
            grp_name: "1L A2".to_string(),
            customer_name: "Velu".to_string(),
            amount: 7000.00,
            mode: Mode::CHEQUE,
            cheque_no: Some("SBIN56789".to_string()),
            bank: Some("State Bank of India".to_string()),
        },
        CollectionModel {
            grp_name: "5L A3".to_string(),
            customer_name: "Mani".to_string(),
            amount: 3500.00,
            mode: Mode::UPI,
            cheque_no: None,
            bank: None,
        },
    ];
    return Json(collection_list);
}